spring.application.name=backend

# 1. Conexion a PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/gymapp_db
# El usuario y contrase�a que se configuro en postgres
spring.datasource.username=postgres
spring.datasource.password=admin

# 2. Configuracion de Hibernate (El motor que traduce Java a SQL)
# Esto hace que se vea en la consola las consultas SQL que Spring Boot ejecuta por detr�s (ideal para buscar errores)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Comportamiento de las tablas
# Como ya se corrio el script SQL a mano y se crearon las tablas, le decimos a Spring que no intente crearlas de nuevo ni borrarlas

spring.jpa.hibernate.ddl-auto=none  #revisar si va esto aqui
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lusenjesdev@gmail.com
spring.mail.password=ktie vpac rtbt znnt   
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true